const samplePatientData = [
  {
    PatientID: "P001",
    FirstName: "Aisha",
    LastName: "Khamis",
    Gender: "F",
    Age: 25,
    Location: "Dar es Salaam",
    EncounterDate: "2025-09-15",
    Symptoms: "Diarrhea, Vomiting",
    Temperature: 38.5,
    DiarrheaSeverity: "Severe",
    LabResult: "Positive",
    WaterSourceQuality: "Unsafe",
    SanitationStatus: "Poor",
  },
  {
    PatientID: "P002",
    FirstName: "Juma",
    LastName: "Mwinyi",
    Gender: "M",
    Age: 40,
    Location: "Mwanza",
    EncounterDate: "2025-09-16",
    Symptoms: "Diarrhea, Abdominal pain",
    Temperature: 37.8,
    DiarrheaSeverity: "Moderate",
    LabResult: "Negative",
    WaterSourceQuality: "Good",
    SanitationStatus: "Adequate",
  },
  {
    PatientID: "P003",
    FirstName: "Fatuma",
    LastName: "Abdalla",
    Gender: "F",
    Age: 32,
    Location: "Arusha",
    EncounterDate: "2025-09-14",
    Symptoms: "Diarrhea",
    Temperature: 38.2,
    DiarrheaSeverity: "Severe",
    LabResult: "Positive",
    WaterSourceQuality: "Unsafe",
    SanitationStatus: "Poor",
  },
  {
    PatientID: "P004",
    FirstName: "Issa",
    LastName: "Kassim",
    Gender: "M",
    Age: 19,
    Location: "Dar es Salaam",
    EncounterDate: "2025-09-13",
    Symptoms: "Vomiting, Fever",
    Temperature: 39.0,
    DiarrheaSeverity: "Mild",
    LabResult: "Negative",
    WaterSourceQuality: "Good",
    SanitationStatus: "Adequate",
  },
  {
    PatientID: "P005",
    FirstName: "Zainab",
    LastName: "Hassan",
    Gender: "F",
    Age: 28,
    Location: "Mbeya",
    EncounterDate: "2025-09-15",
    Symptoms: "Diarrhea, Fever",
    Temperature: 38.7,
    DiarrheaSeverity: "Moderate",
    LabResult: "Positive",
    WaterSourceQuality: "Unsafe",
    SanitationStatus: "Poor",
  },
  {
    PatientID: "P006",
    FirstName: "Mohammed",
    LastName: "Suleiman",
    Gender: "M",
    Age: 35,
    Location: "Dodoma",
    EncounterDate: "2025-09-12",
    Symptoms: "Diarrhea, Nausea",
    Temperature: 37.9,
    DiarrheaSeverity: "Mild",
    LabResult: "Negative",
    WaterSourceQuality: "Good",
    SanitationStatus: "Adequate",
  },
  {
    PatientID: "P007",
    FirstName: "Hawa",
    LastName: "Omari",
    Gender: "F",
    Age: 45,
    Location: "Mwanza",
    EncounterDate: "2025-09-11",
    Symptoms: "Diarrhea, Vomiting",
    Temperature: 39.1,
    DiarrheaSeverity: "Severe",
    LabResult: "Positive",
    WaterSourceQuality: "Unsafe",
    SanitationStatus: "Poor",
  },
  {
    PatientID: "P008",
    FirstName: "Abdul",
    LastName: "Karim",
    Gender: "M",
    Age: 50,
    Location: "Arusha",
    EncounterDate: "2025-09-14",
    Symptoms: "Diarrhea, Abdominal pain",
    Temperature: 38.0,
    DiarrheaSeverity: "Moderate",
    LabResult: "Negative",
    WaterSourceQuality: "Good",
    SanitationStatus: "Adequate",
  },
  {
    PatientID: "P009",
    FirstName: "Sofia",
    LastName: "Ahmed",
    Gender: "F",
    Age: 22,
    Location: "Dodoma",
    EncounterDate: "2025-09-16",
    Symptoms: "Vomiting, Fever",
    Temperature: 37.6,
    DiarrheaSeverity: "Mild",
    LabResult: "Negative",
    WaterSourceQuality: "Good",
    SanitationStatus: "Adequate",
  },
  {
    PatientID: "P010",
    FirstName: "Khalid",
    LastName: "Ismail",
    Gender: "M",
    Age: 30,
    Location: "Mbeya",
    EncounterDate: "2025-09-15",
    Symptoms: "Diarrhea, Nausea",
    Temperature: 38.4,
    DiarrheaSeverity: "Moderate",
    LabResult: "Positive",
    WaterSourceQuality: "Unsafe",
    SanitationStatus: "Poor",
  },
];

export default samplePatientData;
